### PR TITLE
plotLoadings modifications

### PR DESCRIPTION
**Pull request by TuomasBorman**
Now user can also show the sign with colors. This is the default

image

https://github.com/microbiome/miaViz/pull/152

### CODE REVIEW

**Comment by antagomir** [comment]
How about adding "lolliplot plot" option for the layout?

**Comment by TuomasBorman** [comment]
Something like this:

image

**Comment by antagomir** [comment]
Yes, for instance. 

Or, just the lines (with colors, without points). Somehow I like this appearance visually a bit more than bars.

**Comment by TuomasBorman** [comment]
Different plots. Note that adding sign and removing color is hidden options (they are for us to test). By default, if the scale is absolute, color is added. Otherwise the color is not added.

image
image
image
image
image

**Comment by TuomasBorman** [comment]
These are default options for barplot

DEFAULT
image


If absolute.scale is set to FALSE
image

**Comment by antagomir** [comment]
Seems good

**Pull request merged**
