### PR TITLE
Add plotNMDS to miaViz 

### PR DESCRIPTION
**Pull request by theotimeee**
This PR adds `plotNMDS` to miaViz (`plotNMDS` will be deprecated in the mia package).

This PR does not add documentation for `plotNMDS` because it is only a simple wrapper for `scater::plotReducedDim` and it would not fit under already existing man pages.

### CODE REVIEW

**Comment by theotimeee** [comment]
This PR is related to https://github.com/microbiome/mia/pull/517

**Review by TuomasBorman — APPROVED** [review]

**Comment by TuomasBorman** [comment]
Can you add tests?

You can add same 3 lines that were removed in PR https://github.com/microbiome/mia/pull/517/files

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
Seems good. Resolve conflicts.

**Comment by antagomir** [comment]
up

**Comment by theotimeee** [comment]
@TuomasBorman I think we agreed it is better for `plotNMDS` not to have its own manual page and that it does not fit in already existing manual pages in miaViz but I do not think it is possible to leave it without documentation. I tried to export it without documentation but I always get the following R CMD check warning:
```
Undocumented code objects:
    ‘plotNMDS’
  All user-level objects in a package should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```

**Comment by TuomasBorman** [comment]
Alright! You could add minimum documentation. Something like wrapper for plotReducedDim(). And just x parameter.

**Comment by TuomasBorman** [comment]
❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in Rd file 'plotNMDS.Rd'
    ‘...’ ‘ncomponents’

**Review by TuomasBorman — APPROVED** [review]

**Pull request merged**
