### PR TITLE
fix typo error

### PR DESCRIPTION
**Pull request by Vivian-Ginika**
Fix typo errors

### CODE REVIEW

**Comment by antagomir** [comment]
There seems to be a build error:
https://github.com/microbiome/miaViz/actions/runs/4499982965/jobs/7918528335?pr=72

Could you check and see if it is possible to fix.

Run devtools::check() in R before pushing your edits.

**Comment by Daenarys8** [comment]
I'm not sure but this change: assay.type   vssdv = assay_name, assay_name = "counts",' but it seems to be the cause of the failing check. I would suggest you restore the line to original.

**Comment by antagomir** [comment]
This is a bit tricky: the former argument is `assay_name` but in the new Bioconductor releases the packages are all switching to `assay.type` so that is the new one. If that causes problems we could either 1) temporarily use `assay_name` or 2) update the .github/workflows/ so that Github Actions installs the latest Bioconductor devel versions of mia, miaViz, scater, and scuttle.

**Comment by antagomir** [comment]
If support is needed just let us know.

**Comment by antagomir** [comment]
Hi @Vivian-Ginika - are you still working on this one?

**Comment by Vivian-Ginika** [comment]
Hello,

Yes I am, though I am yet to figure it out and had to pause to work on
another project for the contribution on outreachy but I have resumed
working on the PR. Though I will appreciate any help where necessary.

Thank you.

**Comment by antagomir** [comment]
Great. Just let us know when something specific is unclear, and we can take it from there.

**Comment by antagomir** [comment]
Hi @Vivian-Ginika - still failing. Can you actively report here the fail message and seek for help. Otherwise we may miss it.

**Review by antagomir — APPROVED** [review]

**Pull request merged**
