### PR TITLE
Rename agglomerateByRank/Prevalence

### PR DESCRIPTION
**Pull request by 0xMuluh**
See https://github.com/microbiome/mia/issues/392

### CODE REVIEW

**Comment by Daenarys8** [comment]
Should I Update NEWS, DESCRIPTION file (version number)?

**Review by antagomir — APPROVED** [review]

**Review by TuomasBorman — APPROVED** [review]

**Comment by TuomasBorman** [comment]
There is still somewhere agglomerateByRank function

**Comment by Daenarys8** [comment]
I think we can merge this

**Comment by antagomir** [comment]
Hmm checks seem to fail. Need to be fixed before merging.

**Comment by antagomir** [comment]
@Daenarys8

**Comment by antagomir** [comment]
@Daenarys8 @TuomasBorman I am not sure from above what's the status of this one.

**Comment by TuomasBorman** [comment]
We can close this. This renames agglomerateByRank to mergeFeaturesByRank. agglomerateByRank() will be the final name.

**Pull request closed without merging**
