### PR TITLE
Replace getPrevalence with addPrevalence

### PR DESCRIPTION
**Pull request by theotimeee**
After mia PR https://github.com/microbiome/mia/pull/529 that renamed the following functions : 

- `getPrevalence` --> `addPrevalence`
- `getPrevalentAbundance` --> `addPrevalentAbundance`

This PR replaces `getPrevalence` with `addPrevalence` in miaViz.

### CODE REVIEW

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
imo OK to merge

**Review by TuomasBorman — APPROVED** [review]

**Comment by antagomir** [comment]
@thpralas still some failing checks?

**Comment by TuomasBorman** [comment]
Bioconductor devel does not still have latest changes. That is because there is a pending agglomerateByRank issue. The fixes are already merged in devel, so we have to solve the issue before pushing to Bioconductor

**Comment by theotimeee** [comment]
The R CMD check warning should be solved when pushing mia current version to Bioc devel.

**Comment by theotimeee** [comment]
This PR is linked to mia PR https://github.com/microbiome/mia/pull/529 that was closed.

**Pull request closed without merging**
